---
micronaut:
  application:
    name: app-service

---
kafka:
  bootstrap:
    servers: localhost:9092
postgres:
  reactive:
    client:
      port: 5432
      host: localhost
      database: app
      user: app
      password: app
      maxSize: 5
      search_path: app
app:
  group:
    id: app-group
jackson:
  serialization:
    indent-output: false
    write-dates-as-timestamps: false
  deserialization:
    read-date-timestamps-as-nanoseconds: false

micronaut:
  io:
    watch:
      paths: src/main
      restart: true
  server:
    port: 8082
    cors:
      enabled: true